// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCX version 2019.2.0.dev0.
//
// This code was generated with the following parameters:
//
//  {'epsilon': 1e-14,
//   'external_includes': '',
//   'precision': -1,
//   'quadrature_degree': -1,
//   'quadrature_rule': 'auto',
//   'representation': 'auto',
//   'scalar_type': 'double',
//   'tabulate_tensor_void': False}


#pragma once

typedef double ufc_scalar_t;
#include <ufc.h>

#ifdef __cplusplus
extern "C" {
#endif

ufc_finite_element* create_element_e62ea130829c4611b756de2cbd7d0ee4b144b528(void);

ufc_finite_element* create_element_57d632e6da5498ea9b99ecb0a2b64ad86741db6f(void);

ufc_dofmap* create_dofmap_e62ea130829c4611b756de2cbd7d0ee4b144b528(void);

ufc_dofmap* create_dofmap_57d632e6da5498ea9b99ecb0a2b64ad86741db6f(void);

ufc_coordinate_mapping* create_coordinate_mapping_c1881447d6b8c072bffeb3eb309b78481eb4d309(void);

// Helper used to create coordinate map using name given to the
// UFL file.
// This helper is called in user c++ code.
//
ufc_coordinate_mapping* create_coordinate_map_test(void);

ufc_integral* create_integral_cell_otherwise_d43e3c3b1a9850b316c767c17c458fba4fe92f87(void);

ufc_form* create_form_d43e3c3b1a9850b316c767c17c458fba4fe92f87(void);

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
ufc_form* create_form_test_a(void);

// Helper used to create function space using its name, as given in
// the UFL file.
// Note: There are in general more function spaces associated to the form,
//       which is the reason why the helpers takes name as argument.
// This helper is called in user c++ code.
//
ufc_function_space* create_functionspace_form_test_a(const char* fs_name);


#ifdef __cplusplus
}
#endif
